services:
    sugarcrm_rest:
        class: BisonLab\NoOrmBundle\Services\SugarCrmRestReadonly
        arguments:
            base_url: "%sugarcrm_base_url%"
            username: "%sugarcrm_username%"
            password: "%sugarcrm_password%"

    sugarcrm_account_manager:
        class: BisonLab\SugarCrmBundle\Manager\Account
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_manager:
        class: BisonLab\SugarCrmBundle\Manager\Product
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_template_manager:
        class: BisonLab\SugarCrmBundle\Manager\ProductTemplate
        arguments: [ "@sugarcrm_rest" ]
